In [14]:
#import library

import pickle
import json
import pandas as pd
import numpy as np

In [15]:
# Load nama kolom numerikal
with open('list_num_cols.txt', 'r') as file_1:
  list_num_cols = json.load(file_1)
# Load nama kolom kategorikal yang belum di encode
with open('list_cat_cols.txt', 'r') as file_2:
  list_cat_cols = json.load(file_2)
# Load model
with open('best_finance_svr_model.pkl', 'rb') as model:
  svr_finance_model = pickle.load(model)

In [16]:
# Mmebuat dataframe baru
data_inf = {
    'emiten_code' :'ARTO',
    'year' : 2024, 
    'date' : 'Q3', 
    'eps' : 2.59, 
    'per' : 1177.61, 
    'pbv' : 4.99, 
    'bvps' : 611.09, 
    'ebitda' : 109000000000,
    'roa' : 0.13, 
    'roe' : 0.42, 
    'fcf' : 1359000000000, 
    'fcf_ps' : 98.06, 
    'gdp_forecast' : 5, 
    'political_stability' : 17.1,
    'inflation_forecast' : 2.5, 
}

data_inf = pd.DataFrame([data_inf])
data_inf

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast
0,ARTO,2024,Q3,2.59,1177.61,4.99,611.09,109000000000,0.13,0.42,1359000000000,98.06,5,17.1,2.5

In [17]:
#split between numerical and categorical columns

data_inf_num = data_inf[list_num_cols]
data_inf_cat = data_inf[list_cat_cols]
data_inf_final = pd.concat([data_inf_num, data_inf_cat], axis=1)
data_inf_final

,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast,date
0,2.59,1177.61,4.99,611.09,109000000000,0.13,0.42,1359000000000,98.06,5,17.1,2.5,Q3

In [18]:
#predict using linear reg model

y_pred_inf = svr_finance_model.predict(data_inf_final)
y_pred_inf

array([0.45638745])